version: "3.7"
services:
  updater:
    image: updater:latest
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
    volumes:
      - assets:/updater/map-repo/fortress/
      - master_dats:/updater/dats/master/
      - staging_dats:/updater/dats/staging/
    restart: always
  demo-serve:
    image: fortressone/demo-serve:latest
    ports:
      - "80:80"
    volumes:
      - pub-demos:/usr/share/nginx/html/demos/pub
    restart: always
  pubserver:
    depends_on:
      - updater
      - demo-serve
    image: fortressonesv:latest
    command: /fortressonesv/fteqw-sv64 -ip ${FO_IP} +set hostname "${FO_HOSTNAME} Pub" +set rcon_password ${FO_RCON_PASSWORD} +localinfo adminpwd ${FO_ADMINPWD} +exec fo_pubmode.cfg +map 2fort5r
    ports:
      - "27500:27500/udp"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - pub-demos:/fortressonesv/fortress/demos/
    restart: always
volumes:
  pub-demos:
  assets:
  master_dats:
  staging_dats:
