version: "3.7"
services:
  updater:
    image: fortressone/updater:latest
    environment:
      - AWS_SECRET_ACCESS_KEY=${STORAGE_AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${STORAGE_AWS_ACCESS_KEY_ID}
    volumes:
      - assets:/updater/map-repo/fortress/
      - master_dats:/updater/dats/master/
      - staging_dats:/updater/dats/staging/
    restart: always
  demo-serve:
    image: fortressone/demo-serve:latest
    ports:
      - 80:80
    volumes:
      - pub-demos:/usr/share/nginx/html/demos/pub/
      - duel-demos:/usr/share/nginx/html/demos/duel/
      - clan-demos:/usr/share/nginx/html/demos/clan/
      - quad-demos:/usr/share/nginx/html/demos/quad/
      - staging-demos:/usr/share/nginx/html/demos/staging/
    restart: always
  pubserver:
    depends_on:
      - updater
      - demo-serve
    image: fortressone/fortressonesv:latest
    command: |
      - -ip ${FO_IP}
      - +set hostname "${FO_HOSTNAME}"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_pubmode.cfg
      - +map 2fort5r
    ports:
      - 27500:27500/udp
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - pub-demos:/fortressonesv/fortress/demos/
    restart: always
  duelserver:
    depends_on:
      - updater
      - demo-serve
    image: fortressone/fortressonesv:latest
    command: |
      - -ip ${FO_IP}
      - +set hostname "${FO_HOSTNAME}"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_duelmode.cfg
      - +map 1on1r
    ports:
      - 27501:27500/udp
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - duel-demos:/fortressonesv/fortress/demos/
    restart: always
  clanserver:
    depends_on:
      - updater
      - demo-serve
    image: fortressone/fortressonesv:latest
    command: |
      - -ip ${FO_IP}
      - +set hostname "${FO_HOSTNAME}"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_clanmode.cfg
      - +map 2fort5r
    ports:
      - 27502:27500/udp
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - clan-demos:/fortressonesv/fortress/demos/
    restart: always
  quadserver:
    depends_on:
      - updater
      - demo-serve
    image: fortressone/fortressonesv:latest
    command: |
      - -ip ${FO_IP}
      - +set hostname "${FO_HOSTNAME}"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_quadmode.cfg
      - +map 2fort5r
    ports:
      - 27503:27500/udp
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - quad-demos:/fortressonesv/fortress/demos/
    restart: always
  stagingserver:
    depends_on:
      - updater
      - demo-serve
    image: fortressone/fortressonesv:latest
    command: |
      - -ip ${FO_IP}
      - +set hostname "${FO_HOSTNAME}"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_stagingmode.cfg
      - +map 2fort5r
    ports:
      - 27504:27500/udp
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - staging_dats:/fortressonesv/fortress/dats/
      - staging-demos:/fortressonesv/fortress/demos/
    restart: always
volumes:
  pub-demos:
  duel-demos:
  clan-demos:
  quad-demos:
  staging-demos:
  assets:
  master_dats:
  staging_dats:
