version: "3"
services:
  demo-serve:
    image: fortressone/demo-serve:latest
    ports:
      - "80:80"
    volumes:
      - pub-demos:/demo-serve/pub
      - pug-demos:/demo-serve/pug
      - quad-demos:/demo-serve/quad
      - duel-demos:/demo-serve/duel
  pubserver:
    image: fortressone/fortressonesv:latest
    ports:
      - "27500:27500/udp"
    volumes:
      - fortress:/fortressonesv
      - pub-demos:/fortressonesv/fortress/demos
    environment:
      - FO_MODE=pub
      - FO_HOSTNAME="FortressOne Sydney Pub"
      - FO_RCON_PASSWORD=revival
      - FO_ADMINPWD=revival
  duelserver:
    image: fortressone/fortressonesv:latest
    ports:
      - "27501:27500/udp"
    volumes:
      - fortress:/fortressonesv
      - duel-demos:/fortressonesv/fortress/demos
    environment:
      - FO_MODE=duel
      - FO_HOSTNAME="FortressOne Sydney Duel"
      - FO_RCON_PASSWORD=revival
      - FO_ADMINPWD=revival
  pugserver:
    image: fortressone/fortressonesv:latest
    ports:
      - "27502:27500/udp"
    volumes:
      - fortress:/fortressonesv
      - pug-demos:/fortressonesv/fortress/demos
    environment:
      - FO_MODE=pug
      - FO_HOSTNAME="FortressOne Sydney Pug"
      - FO_RCON_PASSWORD=revival
      - FO_ADMINPWD=revival
  quadserver:
    image: fortressone/fortressonesv:latest
    ports:
      - "27503:27500/udp"
    volumes:
      - fortress:/fortressonesv
      - quad-demos:/fortressonesv/fortress/demos
    environment:
      - FO_MODE=quad
      - FO_HOSTNAME="FortressOne Sydney Quad"
      - FO_RCON_PASSWORD=revival
      - FO_ADMINPWD=revival
  server-qwprogs:
    depends_on:
      - pubserver
      - duelserver
      - pugserver
      - quadserver
    image: fortressone/server-qwprogs:latest
    volumes:
      - fortress:/fortressonesv
  map-repo:
    depends_on:
      - pubserver
      - duelserver
      - pugserver
      - quadserver
    image: fortressone/map-repo:latest
    volumes:
      - fortress:/fortressonesv
volumes:
  fortress:
  pub-demos:
  duel-demos:
  pug-demos:
  quad-demos:
