version: "3"
services:
  demo-serve:
    image: fortressone/demo-serve:latest
    ports:
      - "80:80"
    volumes:
      - pub-demos:/demo-serve/pub
      - pug-demos:/demo-serve/pug
      - quad-demos:/demo-serve/quad
      - duel-demos:/demo-serve/duel
    restart: always
  pubserver:
    depends_on:
      - demo-serve
    image: fortressone/fortressonesv:latest
    ports:
      - "27500:27500/udp"
    volumes:
      - fortress:/fortressonesv
      - pub-demos:/fortressonesv/fortress/demos
    environment:
      - FO_MODE=pub
      - FO_HOSTNAME="${FO_HOSTNAME} Pub"
      - FO_RCON_PASSWORD="${FO_RCON_PASSWORD}"
      - FO_ADMINPWD="${FO_ADMINPWD}"
    restart: always
  duelserver:
    depends_on:
      - demo-serve
      - pubserver
    image: fortressone/fortressonesv:latest
    ports:
      - "27501:27500/udp"
    volumes:
      - fortress:/fortressonesv
      - duel-demos:/fortressonesv/fortress/demos
    environment:
      - FO_MODE=duel
      - FO_HOSTNAME="${FO_HOSTNAME} Duel"
      - FO_RCON_PASSWORD="${FO_RCON_PASSWORD}"
      - FO_ADMINPWD="${FO_ADMINPWD}"
    restart: always
  pugserver:
    depends_on:
      - demo-serve
      - pubserver
    image: fortressone/fortressonesv:latest
    ports:
      - "27502:27500/udp"
    volumes:
      - fortress:/fortressonesv
      - pug-demos:/fortressonesv/fortress/demos
    environment:
      - FO_MODE=pug
      - FO_HOSTNAME="${FO_HOSTNAME} Pug"
      - FO_RCON_PASSWORD="${FO_RCON_PASSWORD}"
      - FO_ADMINPWD="${FO_ADMINPWD}"
    restart: always
  quadserver:
    depends_on:
      - demo-serve
      - pubserver
    image: fortressone/fortressonesv:latest
    ports:
      - "27503:27500/udp"
    volumes:
      - fortress:/fortressonesv
      - quad-demos:/fortressonesv/fortress/demos
    environment:
      - FO_MODE=quad
      - FO_HOSTNAME="${FO_HOSTNAME} Quad"
      - FO_RCON_PASSWORD="${FO_RCON_PASSWORD}"
      - FO_ADMINPWD="${FO_ADMINPWD}"
    restart: always
  updater:
    depends_on:
      - pubserver
      - duelserver
      - pugserver
      - quadserver
    image: fortressone/updater:latest
    volumes:
      - fortress:/fortressonesv
    restart: always
volumes:
  fortress:
  pub-demos:
  duel-demos:
  pug-demos:
  quad-demos:
