version: "3"
services:
  server-qwprogs:
    image: fortressone/server-qwprogs:latest
    volumes:
      - fortress:/server-qwprogs/fortress
  map-repo:
    image: fortressone/map-repo:latest
    volumes:
      - fortress:/map-repo/fortress
  pubserver:
    image: fortressone/fortressonesv:latest
    ports:
      - "27500:27500/udp"
    volumes:
      - fortress:/fortressonesv/fortress
    environment:
      - FO_MODE=pub
  duelserver:
    image: fortressone/fortressonesv:latest
    ports:
      - "27501:27500/udp"
    volumes:
      - fortress:/fortressonesv/fortress
    environment:
      - FO_MODE=duel
  pugserver:
    image: fortressone/fortressonesv:latest
    ports:
      - "27502:27500/udp"
    volumes:
      - fortress:/fortressonesv/fortress
    environment:
      - FO_MODE=pug
  clanserver:
    image: fortressone/fortressonesv:latest
    ports:
      - "27503:27500/udp"
    volumes:
      - fortress:/fortressonesv/fortress
    environment:
      - FO_MODE=clan
volumes:
  fortress:
