version: "3"
services:
  server-qwprogs:
    image: fortressone/server-qwprogs:latest
    volumes:
      - fortress:/server-qwprogs/fortress
  map-repo:
    image: fortressone/map-repo:latest
    volumes:
      - fortress:/map-repo/fortress
  pubserver:
    env_file: .env
    image: fortressone/fortressonesv:latest
    ports:
      - "27500:27500/udp"
    volumes:
      - fortress:/fortressonesv/fortress
  duelserver:
    env_file: .env
    image: fortressone/fortressonesv:latest
    ports:
      - "27501:27500/udp"
    volumes:
      - fortress:/fortressonesv/fortress
  pugserver:
    env_file: .env
    image: fortressone/fortressonesv:latest
    ports:
      - "27502:27500/udp"
    volumes:
      - fortress:/fortressonesv/fortress
  clanserver:
    env_file: .env
    image: fortressone/fortressonesv:latest
    ports:
      - "27503:27500/udp"
    volumes:
      - fortress:/fortressonesv/fortress
volumes:
  fortress:
