version: "3"
services:
  map-repo:
    image: map-repo/map-repo:0.0.2
    volumes:
      - maps:/map-repo/fortress/maps
        progs:/map-repo/fortress/progs
        sound:/map-repo/fortress/sound
        lits:/map-repo/fortress/lits
        locs:/map-repo/fortress/locs
        skins:/map-repo/fortress/skins
  pubserver:
    image: fortressone/fortressonesv:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "27500:27500/udp"
    volumes:
      - maps:/fortressonesv/fortress/maps
        progs:/fortressonesv/fortress/progs
        sound:/fortressonesv/fortress/sound
        lits:/fortressonesv/fortress/lits
        locs:/fortressonesv/fortress/locs
        skins:/fortressonesv/fortress/skins
  duelserver:
    image: fortressone/fortressonesv:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "27501:27500/udp"
    volumes:
      - maps:/fortressonesv/fortress/maps
        progs:/fortressonesv/fortress/progs
        sound:/fortressonesv/fortress/sound
        lits:/fortressonesv/fortress/lits
        locs:/fortressonesv/fortress/locs
        skins:/fortressonesv/fortress/skins
  pugserver:
    image: fortressone/fortressonesv:0.0.1
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "27502:27500/udp"
    volumes:
      - maps:/fortressonesv/fortress/maps
        progs:/fortressonesv/fortress/progs
        sound:/fortressonesv/fortress/sound
        lits:/fortressonesv/fortress/lits
        locs:/fortressonesv/fortress/locs
        skins:/fortressonesv/fortress/skins
