---
version: "3.7"
services:
  updater:
    image: fortressone/updater:latest
    restart: always
    environment:
      - AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${S3_AWS_ACCESS_KEY_ID}
      - S3_URI
    volumes:
      - assets:/updater/map-repo/fortress/
      - master_dats:/updater/dats/master/
      - staging_dats:/updater/dats/staging/
      - pub-demos:/updater/demos/pub/
      - duel-demos:/updater/demos/duel/
      - clan-demos:/updater/demos/clan/
      - quad-demos:/updater/demos/quad/
      - staging-demos:/updater/demos/staging/
  pubserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      - -ip ${FO_IP}
      - -port 27500
      - +set hostname "${FO_HOSTNAME} Pub"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_pubmode.cfg
      - +map 2fort5r
    ports:
      - "27500:27500/udp"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - pub-demos:/fortressonesv/fortress/demos/
  duelserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      - -ip ${FO_IP}
      - -port 27501
      - +set hostname "${FO_HOSTNAME} Duel"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_duelmode.cfg
      - +map 1on1r
    ports:
      - "27501:27501/udp"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - duel-demos:/fortressonesv/fortress/demos/
  clanserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      - -ip ${FO_IP}
      - -port 27502
      - +set hostname "${FO_HOSTNAME} Clan"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_clanmode.cfg
      - +map 2fort5r
    ports:
      - "27502:27502/udp"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - clan-demos:/fortressonesv/fortress/demos/
  quadserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      - -ip ${FO_IP}
      - -port 27503
      - +set hostname "${FO_HOSTNAME} Quad"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_quadmode.cfg
      - +map 2fort5r
    ports:
      - "27503:27503/udp"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - quad-demos:/fortressonesv/fortress/demos/
  stagingserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      - -ip ${FO_IP}
      - -port 27504
      - +set hostname "${FO_HOSTNAME} Staging"
      - +set rcon_password "${FO_RCON_PASSWORD}"
      - +localinfo adminpwd "${FO_ADMINPWD}"
      - +exec fo_stagingmode.cfg
      - +map 2fort5r
    ports:
      - "27504:27504/udp"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - staging_dats:/fortressonesv/fortress/dats/
      - staging-demos:/fortressonesv/fortress/demos/
  qwfwd:
    image: fortressone/qwfwd:latest
    stdin_open: true
    tty: true
    restart: always
    command: +set hostname "${FO_HOSTNAME} QWfwd"
    ports:
      - "30000:30000/udp"
volumes:
  pub-demos:
  duel-demos:
  clan-demos:
  quad-demos:
  staging-demos:
  assets:
  master_dats:
  staging_dats:
