---
version: "3.7"
services:
  map-repo:
    image: fortressone/map-repo:latest
    volumes:
      - assets:/map-repo/fortress/
  updater:
    image: fortressone/updater:latest
    restart: always
    depends_on:
      - map-repo
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - S3_DEMO_URI
      - S3_STATS_URI
    volumes:
      - assets:/updater/map-repo/fortress/
      - master_dats:/updater/dats/master/
      - staging_dats:/updater/dats/staging/
      - pub-demos:/updater/demos/pub/
      - duel-demos:/updater/demos/duel/
      - clan-demos:/updater/demos/clan/
      - quad-demos:/updater/demos/quad/
      - staging-demos:/updater/demos/staging/
      - pub-stats:/updater/stats/pub/
      - duel-stats:/updater/stats/duel/
      - clan-stats:/updater/stats/clan/
      - quad-stats:/updater/stats/quad/
      - staging-stats:/updater/stats/staging/
  pubserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27500
      +set hostname "${FO_HOSTNAME} Pub"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_pubmode.cfg
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - pub-demos:/fortressonesv/fortress/demos/
      - pub-stats:/fortressonesv/fortress/data/
  duelserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27501
      +set hostname "${FO_HOSTNAME} Duel"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_duelmode.cfg
      +map 1on1r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - duel-demos:/fortressonesv/fortress/demos/
      - duel-stats:/fortressonesv/fortress/data/
  clanserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27502
      +set hostname "${FO_HOSTNAME} Clan"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_clanmode.cfg
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - clan-demos:/fortressonesv/fortress/demos/
      - clan-stats:/fortressonesv/fortress/data/
  quadserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27503
      +set hostname "${FO_HOSTNAME} Quad"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_quadmode.cfg
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - quad-demos:/fortressonesv/fortress/demos/
      - quad-stats:/fortressonesv/fortress/data/
  trickserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27504
      +set hostname "${FO_HOSTNAME} Trick"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_pubmode.cfg
      +sv_cheats 1
      +map rj101_b3
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - pub-demos:/fortressonesv/fortress/demos/
      - pub-stats:/fortressonesv/fortress/data/
  pubnobhserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27505
      +set hostname "${FO_HOSTNAME} No Bunny Pub"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_pubmode.cfg
      +set pm_bunnyspeedcap 1
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - pub-demos:/fortressonesv/fortress/demos/
      - pub-stats:/fortressonesv/fortress/data/
  stagingserver:
    image: fortressone/fortressonesv:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27510
      +set hostname "${FO_HOSTNAME} Staging"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_stagingmode.cfg
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - staging_dats:/fortressonesv/fortress/dats/
      - staging-demos:/fortressonesv/fortress/demos/
      - staging-stats:/fortressonesv/fortress/data/
  dmserver:
    image: niclaslindstedt/nquakesv:latest
    stdin_open: true
    tty: true
    restart: always
    environment:
      - HOSTNAME=${FO_HOSTNAME} KTX
      - PORT=27600
      - SERVER_ADMIN=zel@fortressone.org
      - RCON_PASSWORD=${FO_RCON_PASSWORD}
      - SERVER_IP=${FO_IP}
    network_mode: "host"
  raceserver:
    image: fortressone/nquakesv-race:latest
    stdin_open: true
    tty: true
    restart: always
    environment:
      - HOSTNAME=${FO_HOSTNAME} KTX Race
      - PORT=27601
      - SERVER_ADMIN=zel@fortressone.org
      - RCON_PASSWORD=${FO_RCON_PASSWORD}
      - SERVER_IP=${FO_IP}
    network_mode: "host"
  qwfwd:
    image: fortressone/qwfwd:latest
    stdin_open: true
    tty: true
    restart: always
    command: |
      30000 0.0.0.0
      +set hostname "${FO_HOSTNAME} QWfwd"
    network_mode: "host"
volumes:
  pub-demos:
  duel-demos:
  clan-demos:
  quad-demos:
  staging-demos:
  pub-stats:
  duel-stats:
  clan-stats:
  quad-stats:
  staging-stats:
  assets:
  master_dats:
  staging_dats:
