#!/usr/bin/env bash

set -e
set -u

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
source "$DIR/shared"

source_and_deploy () {
  source_docker_machine_env "${1}"
  source_docker_compose_env "${1}"
  docker-compose -f production.yml down --remove-orphans
  docker-compose -f production.yml pull
  docker-compose -f production.yml up -d
}

for m in "${aws_machines[@]}"
do
  echo Deploying "${m}"
  (
  source_aws_env "${m}"
  source_and_deploy "${m}"
  )
done

for m in "${other_machines[@]}"
do
  echo Deploying "${m}"
  (
  source_and_deploy "${m}"
  )
done
