#!/usr/bin/env bash

set -e
set -u

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
source "$DIR/shared"

restart_docker_compose () {
  source_docker_machine_env "${1}"
  source_docker_compose_env "${1}"
  docker-compose -f production.yml restart
}

for m in "${aws_machines[@]}"
do
  echo Restarting "${m}"
  (
  source_aws_env "${m}"
  restart_docker_compose "${m}"
  )
done

for m in "${other_machines[@]}"
do
  echo Restarting "${m}"
  (
  restart_docker_compose "${m}"
  )
done
