#!/usr/bin/env bash

set -e
set -u

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
source "$DIR/shared"

print_stats () {
  source_docker_machine_env "${1}"
  source_docker_compose_env "${1}"
  docker stats --no-stream
}

for m in "${aws_machines[@]}"
do
  echo Stats for "${m}"
  (
  source_aws_env "${m}"
  print_stats "${m}"
  )
done

for m in "${other_machines[@]}"
do
  echo Stats for "${m}"
  (
  print_stats "${m}"
  )
done
